# This is a text analyzer for U4Ea
import lyricsgenius as lg
import re
import os

# This is to process the lyric generation
inputArtist = ""
songName = ""
genius = lg.Genius('wFfUqG6CeAxJ3ceIN88GdO5EIWBXcSsfZSDNT4vx_QfT7PHek9H6OobdT_c-4ri6', skip_non_songs=True,
                   excluded_terms=["(Remix)", "(Live)"], remove_section_headers=True)


def get_lyrics(artist, song):
    songHolder = genius.search_song(song, artist)
    return songHolder.lyrics


lyricString = re.sub(r'[\(\[].*?[\)\]]', '', get_lyrics(inputArtist, songName))
lyricString = os.linesep.join([s for s in lyricString.splitlines() if s])
inputList = lyricString.lower().split()

# This is the dictionaries for each category, where each word has an assigned score which indicates whether it is
# positive or negative
unityDict = {
    "cynical": -1, "contemptuous": -1, "derisive": -1, "ironic": -1, "misanthropic": -1, "misanthropical": -1,
    "mocking": -1, "pessimistic": -1, "sarcastic": -1, "sardonic": -1, "scoffing": -1, "scornful": -1,
    "skeptical": -1, "sneering": -1, "suspicious": -1, "unbelieving": -1, "wry": -1, "cynically": -1,
    "materialistic": -1, "greedy": -1, "profane": -1, "secular": -1, "sensual": -1, "temporal": -1, "acquisitive": -1,
    "banausic": -1, "carnal": -1, "earthly-minded": -1, "earthy": -1, "material": -1, "mundane": -1,
    "object-oriented": -1, "possessive": -1, "terrestrial": -1, "unspiritual": -1, "nonmaterialistic": -1,
    "confused": -1, "baffled": -1, "befuddled": -1, "bewildered": -1, "dazed": -1, "disorganized": -1, "distracted": -1,
    "muddled": -1, "perplexed": -1, "perturbed": -1, "puzzled": -1, "abashed": -1, "addled": -1, "discombobulated": -1,
    "disconcerted": -1, "flummoxed": -1, "flustered": -1, "gone": -1, "misled": -1, "nonplussed": -1, "stumped": -1,
    "thrown": -1, "unscrewed": -1, "unzipped": -1, "woolly": -1, "at a loss": -1, "at sea": -1,
    "at sixes and sevens": -1, "come apart": -1, "fouled-up": -1, "glassy-eyed": -1, "mixed up": -1, "not with it": -1,
    "out to lunch": -1, "punch-drunk": -1, "punchy": -1, "screwy": -1, "shook-up": -1, "shot to pieces": -1,
    "slaphappy": -1, "spaced out": -1, "taken aback": -1, "thrown off balance": -1, "unglued": -1, "consciousness": 1,
    "alertness": 1, "apprehension": 1, "awareness": 1, "recognition": 1, "sensibility": 1, "care": 1, "carefulness": 1,
    "cognizance": 1, "concern": 1, "heed": 1, "heedfulness": 1, "mindfulness": 1, "realization": 1, "regard": 1,
    "underconsciousness": 1, "cleansed": 1, "blank": 1, "bright": 1, "clear": 1, "elegant": 1, "fresh": 1,
    "graceful": 1, "hygienic": 1, "immaculate": 1, "neat": 1, "orderly": 1, "pure": 1, "simple": 1, "spotless": 1,
    "squeaky clean": 1, "tidy": 1, "unblemished": 1, "washed": 1, "laundered": 1, "shining": 1, "sparkling": 1,
    "speckless": 1, "stainless": 1, "trim": 1, "vanilla": 1, "delicate": 1, "dirtless": 1, "faultless": 1,
    "flawless": 1, "neat as a button": 1, "neat as a pin": 1, "sanitary": 1, "snowy": 1, "spick-and-span": 1,
    "taintless": 1, "unpolluted": 1, "unsmudged": 1, "unsoiled": 1, "unspotted": 1, "unstained": 1, "unsullied": 1,
    "untarnished": 1, "well-kept": 1, "empathy": 1, "affinity": 1, "appreciation": 1, "compassion": 1, "insight": 1,
    "pity": 1, "rapport": 1, "sympathy": 1, "warmth": 1, "communion": 1, "comprehension": 1, "concord": 1,
    "recognition": 1, "responsiveness": 1, "soul": 1, "being on same wavelength": 1, "being there for someone": 1,
    "community of interests": 1, "cottoning to": 1, "good vibrations": 1, "hitting it off": 1, "picking up on": 1,
    "bliss": 1, "euphoria": 1, "happiness": 1, "joy": 1, "paradise": 1, "beatitude": 1, "blessedness": 1, "cool": 1,
    "felicity": 1, "gladness": 1, "heaven": 1, "rapture": 1, "miraculous": 1, "amazing": 1, "astonishing": 1,
    "astounding": 1, "awesome": 1, "extraordinary": 1, "freakish": 1, "incredible": 1, "inexplicable": 1, "magical": 1,
    "marvelous": 1, "monstrous": 1, "phenomenal": 1, "spectacular": 1, "strange": 1, "superhuman": 1, "supernatural": 1,
    "unbelievable": 1, "unreal": 1, "wondrous": 1, "anomalous": 1, "fabulous": 1, "heavy": 1, "numinous": 1,
    "preternatural": 1, "prodigious": 1, "staggering": 1, "stupefying": 1, "stupendous": 1, "superior": 1,
    "supermundane": 1, "supranatural": 1, "thaumaturgic": 1, "the utmost": 1, "unaccountable": 1, "unearthly": 1,
    "unimaginable": 1, "wonderworking": 1, "miraculously": 1, "wise": 1, "astute": 1, "aware": 1, "careful": 1,
    "educated": 1, "enlightened": 1, "experienced": 1, "informed": 1, "judicious": 1, "knowledgeable": 1,
    "perceptive": 1, "prudent": 1, "rational": 1, "sagacious": 1, "sane": 1, "sensible": 1, "smart": 1, "thoughtful": 1,
    "wary": 1, "well-informed": 1, "contemplative": 1, "keen": 1, "knowing": 1, "sage": 1, "sensing": 1, "sharp": 1,
    "sound": 1, "understanding": 1, "calculating": 1, "clever": 1, "cogitative": 1, "crafty": 1, "cunning": 1,
    "discerning": 1, "discreet": 1, "erudite": 1, "foresighted": 1, "insightful": 1, "intuitive": 1, "perspicacious": 1,
    "reflective": 1, "sapient": 1, "scholarly": 1, "shrewd": -1, "sophic": 1, "tactful": 1, "taught": 1,
    "witty": 1, "wisely": 1, "wiser": 1, "wisest": 1, "spiritual": 1, "divine": 1, "metaphysical": 1, "sacred": 1,
    "devotional": 1,
    "holy": 1, "intangible": 1, "airy": 1, "asomatous": 1, "discarnate": 1, "disembodied": 1, "ethereal": 1,
    "extramundane": 1,
    "ghostly": 1, "immaterial": 1, "incorporeal": 1, "nonmaterial": 1, "nonphysical": 1, "platonic": 1, "pure": 1,
    "rarefied": 1, "refined": 1, "supernal": 1, "unfleshly": 1, "unphysical": 1, "nonspiritual": 1, "spiritually": 1,
    "unspiritual": 1, "open-minded": 1, "approachable": 1, "impartial": 1, "observant": 1, "tolerant": 1,
    "acceptant": 1,
    "acceptive": 1, "broad-minded": 1, "interested": 1, "open to suggestions": 1, "perceptive": 1, "persuadable": 1,
    "swayable": 1, "unbiased": 1, "understanding": 1, "open-mindedly": 1, "open-mindedness": 1, "aware": 1, "alive": 1,
    "appreciative": 1, "apprehensive": 1, "attentive": 1, "awake": 1, "cognizant": 1, "conscious": 1, "familiar": 1,
    "informed": 1, "mindful": 1, "receptive": 1, "wise": 1, "acquainted": 1, "alert": 1, "appraised": 1, "apprised": 1,
    "au courant": 1, "cool": 1, "enlightened": 1, "go-go": 1, "groovy": 1, "grounded": 1, "heedful": 1, "hip": 1,
    "in the know": 1, "in the picture": 1, "into": 1, "know the score": 1, "know what's what": 1, "know-how": 1,
    "knowing": 1, "latched on": 1, "on the beam": 1, "perceptive": 1, "plugged in": 1, "savvy": 1,
    "sensible": 1, "sentient": 1, "sharp": 1, "tuned-in": 1, "up on": 1, "wise to": 1, "wised up": 1, "with it": 1,
    "awareness": 1, "self-aware": 1
}

intuitionDict = {
    "distracted": -1, "disturbed": -1, "panicked": -1, "distressed": -1, "distraught": -1, "frenzied": -1,
    "distractedly": -1, "undistracted": -1, "closed-minded": -1, "inflexible": -1, "obstinate": -1,
    "pigheaded": -1, "rigid": -1, "forgetful": -1, "careless": -1, "distracted": -1, "inattentive": -1,
    "sloppy": -1, "unmindful": -1, "absent": -1, "absent-minded": -1, "abstracted": -1, "airheaded": -1,
    "amnemonic": -1, "amnesic": -1, "asleep on the job": -1, "bemused": -1, "dreamy": -1, "heedless": -1, "lax": -1,
    "like an absent-minded professor": -1, "looking out window": -1, "mooning": -1, "moony": -1, "neglectful": -1,
    "negligent": -1, "nirvanic": -1, "not on the job": -1, "oblivious": -1, "out of it": -1, "out to lunch": -1,
    "pipe dreaming": -1, "preoccupied": -1, "remiss": -1, "slack": -1, "unwitting": -1, "woolgathering": -1,
    "forgetfulness": -1, "unforgetful": -1, "insight": 1, "acumen": 1, "intuition": 1, "judgment": 1, "observation": 1,
    "understanding": 1, "vision": 1, "wisdom": 1, "click": 1, "common sense": 1, "comprehension": 1, "discernment": 1,
    "divination": 1, "drift": 1, "penetration": 1, "perception": 1, "perceptivity": 1, "perspicacity": 1,
    "sagaciousness": 1, "sagacity": 1, "sapience": 1, "shrewdness": 1, "wavelength": 1, "sageness": 1, "insights": 1,
    "composure": 1, "aplomb": 1, "dignity": 1, "equanimity": 1, "equilibrium": 1, "fortitude": 1, "poise": 1,
    "self-assurance": 1, "self-control": 1, "serenity": 1, "sobriety": 1, "accord": 1, "assurance": 1, "balance": 1,
    "calm": 1, "contentment": 1, "control": 1, "cool": 1, "coolness": 1, "dispassion": 1, "ease": 1, "evenness": 1,
    "harmony": 1, "imperturbability": 1, "moderation": 1, "nonchalance": 1, "placidity": 1, "polish": 1, "quiet": 1,
    "quietude": 1, "repose": 1, "sang-froid": 1, "sedateness": 1, "self-possession": 1, "stability": 1,
    "tranquility": 1, "cool head": 1, "coolheadedness": 1, "even temper": 1, "inexcitability": 1, "levelheadedness": 1,
    "peace of mind": 1, "presence of mind": 1, "peace": 1, "accord": 1, "friendship": 1, "love": 1, "reconciliation": 1,
    "truce": 1, "unity": 1, "amity": 1, "armistice": 1, "cessation": 1, "conciliation": 1, "concord": 1,
    "neutrality": 1,
    "order": 1, "pacification": 1, "pacifism": 1, "treaty": 1, "unanimity": 1, "union": 1, "integrity": 1,
    "honesty": 1, "principle": 1, "probity": 1, "purity": 1, "rectitude": 1, "sincerity": 1, "virtue": 1, "candor": 1,
    "forthrightness": 1, "goodness": 1, "honestness": 1, "honorableness": 1, "incorruptibility": 1, "incorruption": 1,
    "righteousness": 1, "straightforwardness": 1, "secure": 1, "protected": 1, "defended": 1, "guarded": 1,
    "sheltered": 1, "shielded": 1, "immune": 1, "impregnable": 1, "out of harm's way": 1, "riskless": 1,
    "unassailable": 1, "undamaged": 1, "unharmed": 1, "securable": 1, "secured": 1, "securely": 1, "securing": 1,
    "unsecurely": 1, "tranquil": 1, "amicable": 1, "balmy": 1, "calm": 1, "easygoing": 1, "gentle": 1, "mild": 1,
    "pastoral": 1, "placid": 1, "restful": 1, "sedate": 1, "serene": 1, "sober": 1, "stable": 1, "tame": 1,
    "temperate": 1, "agreeable": 1, "at ease": 1, "at peace": 1, "collected": 1, "comforting": 1, "composed": 1,
    "cool": 1, "easy": 1, "even": 1, "even-tempered": 1, "halcyon": 1, "hushed": 1, "lenient": 1, "low": 1,
    "measured": 1, "moderate": 1, "murmuring": 1, "pacific": 1, "paradisiacal": 1, "patient": 1, "pleasing": 1,
    "poised": 1, "possessed": 1, "reasonable": 1, "sedative": 1, "smooth": 1, "soft": 1, "soothing": 1, "still": 1,
    "undisturbed": 1, "unexcitable": 1, "unexcited": 1, "unperturbed": 1, "unruffled": 1, "untroubled": 1,
    "whispering": 1, "tranquilly": 1, "imagination": 1, "artistry": 1, "awareness": 1, "fancy": 1, "fantasy": 1,
    "idea": 1, "image": 1, "imagery": 1, "ingenuity": 1, "insight": 1, "inspiration": 1, "intelligence": 1,
    "inventiveness": 1, "originality": 1, "resourcefulness": 1, "thought": 1, "vision": 1, "wit": 1, "acuteness": 1,
    "chimera": 1, "cognition": 1, "conception": 1, "creation": 1, "creativity": 1, "enterprise": 1, "fabrication": 1,
    "ideality": 1, "illusion": 1, "invention": 1, "notion": 1, "perceptibility": 1, "realization": 1, "sally": 1,
    "supposition": 1, "thoughtfulness": 1, "unreality": 1, "verve": 1, "visualization": 1, "wittiness": 1,
    "creative thought": 1, "flight of fancy": 1, "mental agility": 1
}

resolveDict = {
    "out of control": -1, "carried away": -1, "disorderly": -1, "out of hand": -1, "rebellious": -1,
    "uncontrollable": -1, "ungovernable": -1, "unmanageable": -1, "unruly": -1, "wild": -1, "communicative": 1,
    "candid": 1, "chatty": 1, "conversational": 1, "demonstrative": 1, "expansive": 1, "talkative": 1,
    "communicable": 1, "conversable": 1, "effusive": 1, "enlightening": 1, "forthcoming": 1, "frank": 1,
    "garrulous": 1, "gushing": 1, "loquacious": 1, "open": 1, "outgoing": 1, "unreserved": 1, "voluble": 1,
    "truthful": 1, "believable": 1, "candid": 1, "correct": 1, "factual": 1, "forthright": 1, "precise": 1,
    "realistic": 1, "reliable": 1, "sincere": 1, "straightforward": 1, "true": 1, "trustworthy": 1, "exact": 1,
    "faithful": 1, "frank": 1, "guileless": 1, "ingenuous": 1, "just": 1, "kosher": 1, "legit": 1, "like it is": 1,
    "literal": 1, "on the level": 1, "on the up and up": 1, "open": 1, "outspoken": 1, "plainspoken": 1, "real": 1,
    "righteous": 1, "scrupulous": 1, "square": 1, "straight": 1, "true-blue": 1, "truth-telling": 1, "unfeigned": 1,
    "unreserved": 1, "veracious": 1, "veritable": 1, "truthfully": 1, "truthfulness": 1, "expressive": 1,
    "articulate": 1, "artistic": 1, "colorful": 1, "dramatic": 1, "eloquent": 1, "energetic": 1, "passionate": 1,
    "poignant": 1, "striking": 1, "suggestive": 1, "thoughtful": 1, "vivid": 1, "alive": 1, "allusive": 1,
    "brilliant": 1, "demonstrative": 1, "emphatic": 1, "forcible": 1, "graphic": 1, "indicative": 1, "ingenious": 1,
    "lively": 1, "masterly": 1, "meaningful": 1, "mobile": 1, "moving": 1, "pathetic": 1, "pictorial": 1,
    "picturesque": 1, "pointed": 1, "pregnant": 1, "representative": 1, "responsive": 1, "revelatory": 1, "showy": 1,
    "significant": 1, "silver-tongued": 1, "spirited": 1, "stimulating": 1, "stirring": 1, "strong": 1,
    "sympathetic": 1, "tender": 1, "touching": 1, "understanding": 1, "warm": 1, "expressiveness": 1, "artistic": 1,
    "aesthetic": 1, "creative": 1, "decorative": 1, "dramatic": 1, "imaginative": 1, "musical": 1, "cultivated": 1,
    "cultured": 1, "elegant": 1, "exquisite": 1, "fine": 1, "graceful": 1, "grand": 1, "harmonious": 1, "ideal": 1,
    "ornamental": 1, "pictorial": 1, "picturesque": 1, "pleasing": 1, "poetic": 1, "refined": 1, "rhythmical": 1,
    "sensitive": 1, "stimulating": 1, "stylish": 1, "sublime": 1, "tasteful": 1, "artistically": 1, "purpose": 1,
    "ambition": 1, "aspiration": 1, "desire": 1, "determination": 1, "direction": 1, "function": 1, "goal": 1,
    "idea": 1, "intent": 1, "objective": 1, "plan": 1, "principle": 1, "project": 1, "reason": 1, "scheme": 1,
    "scope": 1, "target": 1, "view": 1, "wish": 1, "animus": 1, "bourn": 1, "calculation": 1, "design": 1,
    "destination": 1, "dream": 1, "drift": 1, "end": 1, "expectation": 1, "hope": 1, "mecca": 1, "mission": 1,
    "object": 1, "point": 1, "premeditation": 1, "proposal": 1, "proposition": 1, "prospect": 1, "resolve": 1,
    "will": 1,
    "big idea": 1, "intendment": 1, "ulterior motive": 1, "whatfor": 1, "where one's headed": 1, "whole idea": 1,
    "why and wherefore": 1, "whyfor": 1, "purposed": 1, "purposes": 1, "repurpose": 1, "unpurposed": 1, "open": 1,
    "accessible": 1, "clear": 1, "free": 1, "susceptible": 1, "wide": 1, "agape": 1, "bare": 1, "cleared": 1,
    "disclosed": 1, "emptied": 1, "expanded": 1, "exposed": 1, "extended": 1, "gaping": 1, "patent": 1, "peeled": 1,
    "removed": 1, "rent": 1, "revealed": 1, "rolling": 1, "stripped": 1, "unbarred": 1, "unblocked": 1, "unbolted": 1,
    "unburdened": 1, "uncluttered": 1, "uncovered": 1, "unfolded": 1, "unfurled": 1, "unlocked": 1, "unplugged": 1,
    "unsealed": 1, "vacated": 1, "yawning": 1, "airy": 1, "ajar": 1, "dehiscent": 1, "expansive": 1, "extensive": 1,
    "made passable": 1, "naked": 1, "navigable": 1, "passable": 1, "patulous": 1, "ringent": 1, "spacious": 1,
    "spread-out": 1, "unimpeded": 1, "unobstructed": 1, "unshut": 1, "unstopped": 1, "opened": 1, "opening": 1,
    "openly": 1, "openness": 1, "of service": 1, "involved": 1, "active": 1, "auxiliary": 1, "conducive": 1,
    "contributory": 1, "helpful": 1, "helping": 1, "of help": 1, "partly responsible": 1, "serviceable": 1,
    "subsidiary": 1, "useful": 1, "sophistication": 1, "composure": 1, "elegance": 1, "finesse": 1, "poise": 1,
    "refinement": 1, "tact": 1, "worldliness": 1, "urbanity": 1, "savoir faire": 1, "savoir vivre": 1,
    "social grace": 1,
    "worldly wisdom": 1, "protection": 1, "conservation": 1, "insurance": 1, "preservation": 1, "safeguard": 1,
    "safety": 1, "security": 1, "shelter": 1, "stability": 1, "aegis": 1, "armament": 1, "armor": 1, "assurance": 1,
    "barrier": 1, "buffer": 1, "bulwark": 1, "camouflage": 1, "certainty": 1, "charge": 1, "cover": 1, "custody": 1,
    "defense": 1, "fix": 1, "guard": 1, "invulnerability": 1, "reassurance": 1, "refuge": 1, "safekeeping": 1,
    "salvation": 1, "screen": 1, "self-defense": 1, "shield": 1, "strength": 1, "surety": 1, "tutelage": 1,
    "umbrella": 1, "ward": 1, "guarding": 1, "protecting": 1, "wardship": 1
}

harmonyDict = {
    "demanding": -1, "ambitious": -1, "critical": -1, "difficult": -1, "exacting": -1, "exhausting": -1, "hard": -1,
    "onerous": -1, "pressing": -1, "strict": -1, "stringent": -1, "taxing": -1, "tough": -1, "troublesome": -1,
    "trying": -1, "nagging": -1, "wearing": -1, "backbreaker": -1, "bothersome": -1, "clamorous": -1, "dictatorial": -1,
    "exigent": -1, "fussy": -1, "grievous": -1, "imperious": -1, "importunate": -1, "insistent": -1, "oppressive": -1,
    "querulous": -1, "weighty": -1, "jealous": -1, "anxious": -1, "apprehensive": -1, "attentive": -1, "envious": -1,
    "intolerant": -1, "possessive": -1, "protective": -1, "resentful": -1, "skeptical": -1, "suspicious": -1,
    "begrudging": -1, "covetous": -1, "demanding": -1, "doubting": -1, "emulous": -1, "envying": -1, "grabby": -1,
    "grasping": -1, "green-eyed": -1, "grudging": -1, "guarded": -1, "invidious": -1, "jaundiced": -1,
    "mistrustful": -1,
    "monopolizing": -1, "possessory": -1, "questioning": -1, "rival": -1, "solicitous": -1, "vigilant": -1,
    "watchful": -1, "zealous": -1, "critical": -1, "demanding": -1, "analytical": -1, "belittling": -1, "biting": -1,
    "calumniatory": -1, "captious": -1, "carping": -1, "caviling": -1, "cavillous": -1, "censorious": -1,
    "censuring": -1, "choleric": -1, "condemning": -1, "critic": -1, "cutting": -1, "cynical": -1, "demeaning": -1,
    "derogatory": -1, "diagnostic": -1, "disapproving": -1, "discerning": -1, "discriminating": -1, "disparaging": -1,
    "exacting": -1, "exceptive": -1, "finicky": -1, "fussy": -1, "hairsplitting": -1, "humbling": -1,
    "hypercritical": -1, "lowering": -1, "nagging": -1, "niggling": -1, "nit-picking": -1, "overcritical": -1,
    "particular": -1, "penetrating": -1, "reproachful": -1, "sarcastic": -1, "satirical": -1, "scolding": -1,
    "severe": -1, "sharp": -1, "trenchant": -1, "withering": -1, "criticality": -1, "critically": -1,
    "criticalness": -1, "anti-social": -1, "antisocial": -1, "egoistic": -1, "egotistical": -1, "eremitic": -1,
    "hating": -1, "inhumane": -1, "malevolent": -1, "misanthropical": -1, "reclusive": -1, "reserved": -1,
    "sarcastic": -1, "selfish": -1, "solitary": -1, "standoffish": -1, "unfriendly": -1, "sincerity": 1, "candor": 1,
    "earnestness": 1, "frankness": 1, "genuineness": 1, "goodwill": 1, "impartiality": 1, "probity": 1,
    "reliability": 1, "seriousness": 1, "trustworthiness": 1, "truth": 1, "truthfulness": 1, "veracity": 1,
    "artlessness": 1, "heart": 1, "honor": 1, "innocence": 1, "justice": 1, "openness": 1, "singleness": 1,
    "wholeheartedness": 1, "bona fides": 1, "good faith": 1, "guilelessness": 1, "sincereness": 1, "connection": 1,
    "contact": 1, "network": 1, "relation": 1, "acquaintance": 1, "agent": 1, "ally": 1, "associate": 1,
    "association": 1, "friend": 1, "go-between": 1, "intermediary": 1, "kin": 1, "kindred": 1, "kinship": 1,
    "mentor": 1, "messenger": 1, "reciprocity": 1, "relative": 1, "sponsor": 1, "connectional": 1, "connections": 1,
    "hopeful": 1, "buoyant": 1, "cheerful": 1, "comfortable": 1, "confident": 1, "eager": 1, "enthusiastic": 1,
    "rosy": 1,
    "sanguine": 1, "trusting": 1, "upbeat": 1, "calm": 1, "content": 1, "faithful": 1, "high": 1, "anticipating": 1,
    "anticipative": 1, "assured": 1, "at ease": 1, "blithe": 1, "elated": 1, "emboldened": 1, "expecting": 1,
    "forward-looking": 1, "hoping": 1, "inspirited": 1, "keeping the faith": 1, "lighthearted": 1,
    "looking forward to": 1, "reassured": 1, "rose-colored": 1, "satisfied": 1, "serene": 1, "trustful": 1,
    "unflagging": 1, "hopefulness": 1, "unhopeful": 1, "loving": 1, "admiring": 1, "affectionate": 1, "amiable": 1,
    "attentive": 1, "benevolent": 1, "caring": 1, "considerate": 1, "cordial": 1, "dear": 1, "devoted": 1, "doting": 1,
    "earnest": 1, "faithful": 1, "friendly": 1, "generous": 1, "loyal": 1, "passionate": 1, "romantic": 1,
    "thoughtful": 1, "warm": 1, "attached": 1, "concerned": 1, "enamored": 1, "infatuated": 1, "liking": 1,
    "respecting": 1, "tender": 1, "valuing": 1, "amatory": 1, "amorous": 1, "anxious": 1, "appreciative": 1,
    "ardent": 1, "demonstrative": 1, "erotic": 1, "expressive": 1, "fervent": 1, "fond": 1, "idolatrous": 1,
    "impassioned": 1, "kind": 1, "reverent": 1, "reverential": 1, "sentimental": 1, "solicitous": 1, "warm-hearted": 1,
    "worshipful": 1, "zealous": 1, "lovingly": 1, "lovingness": 1, "unloving": 1, "positive": 1, "clear": 1,
    "conclusive": 1, "confident": 1, "decisive": 1, "specific": 1, "absolute": 1, "affirmative": 1, "cold": 1,
    "concrete": 1, "express": 1, "firm": 1, "perfect": 1, "rank": 1, "real": 1, "actual": 1, "assured": 1,
    "categorical": 1, "clear-cut": 1, "cocksure": 1, "complete": 1, "consummate": 1, "convinced": 1, "decided": 1,
    "direct": 1, "downright": 1, "explicit": 1, "factual": 1, "forceful": 1, "forcible": 1, "genuine": 1, "hard": 1,
    "inarguable": 1, "incontestable": 1, "incontrovertible": 1, "indisputable": 1, "indubitable": 1, "irrefutable": 1,
    "out-and-out": 1, "outright": 1, "sure": 1, "thorough": 1, "thoroughgoing": 1, "unambiguous": 1, "undeniable": 1,
    "unequivocal": 1, "unmistakable": 1, "unmitigated": 1, "positiveness": 1, "positives": 1, "forgiving": 1,
    "lenient": 1, "magnanimous": 1, "merciful": 1, "accepting": 1, "kind": 1, "compassionate": 1, "benevolent": 1,
    "charitable": 1, "humane": 1, "merciful": 1, "sympathetic": 1, "warm": 1, "warmhearted": 1, "forbearing": 1,
    "pitying": 1, "sparing": 1, "tender": 1, "understanding": 1, "all heart": 1, "being big": 1, "bleeding-heart": 1,
    "commiserative": 1, "going easy on": 1, "humanitarian": 1, "indulgent": 1, "kindhearted": 1, "kindly": 1,
    "lenient": 1, "living with": 1, "old softie": 1, "piteous": 1, "responsive": 1, "soft-shell": 1, "softhearted": 1,
    "tenderhearted": 1, "compassionately": 1, "compassionateness": 1, "uncompassionate": 1, "empathic": 1,
    "compassionate": 1, "empathetic": 1, "feeling": 1, "sensitive": 1, "sympathetic": 1
}

miraclesDict = {
    "lethargic": -1, "apathetic": -1, "dull": -1, "lackadaisical": -1, "laid-back": -1, "languid": -1, "listless": -1,
    "passive": -1, "sleepy": -1, "blah": -1, "comatose": -1, "debilitated": -1, "dilatory": -1, "dopey": -1,
    "dormant": -1, "draggy": -1, "drowsy": -1, "enervated": -1, "having spring fever": -1, "heavy": -1, "idle": -1,
    "impassive": -1, "inactive": -1, "indifferent": -1, "inert": -1, "laggard": -1, "languorous": -1, "moony": -1,
    "nebbish": -1, "out of it": -1, "phlegmatic": -1, "sleepyhead": -1, "slothful": -1, "slow": -1, "slumberous": -1,
    "snoozy": -1, "somnolent": -1, "spiritless": -1, "stolid": -1, "stretchy": -1, "stupefied": -1, "supine": -1,
    "torpid": -1, "wimpy": -1, "lethargically": -1, "addicted": -1, "absorbed": -1, "accustomed": -1, "attached": -1,
    "devoted": -1, "hooked": -1, "inclined": -1, "obsessed": -1, "disposed": -1, "habituated": -1, "hyped": -1,
    "imbued": -1, "predisposed": -1, "dependent": -1, "fond": 1, "given over to": -1, "given to": -1, "prone to": -1,
    "spaced out": -1, "strung-out": -1, "under the influence": -1, "used to": -1, "wedded to": -1, "confident": 1,
    "assured": 1, "convinced": 1, "positive": 1, "sure": 1, "upbeat": 1, "hopeful": 1, "optimistic": 1, "sanguine": 1,
    "counting on": 1, "expectant": 1, "having faith in": 1, "secure": 1, "confidently": 1, "unconfident": 1,
    "discipline": 1, "control": 1, "development": 1, "education": 1, "method": 1, "practice": 1, "preparation": 1,
    "regulation": 1, "restraint": 1, "self-control": 1, "self-restraint": 1, "will": 1, "conduct": 1, "cultivation": 1,
    "curb": 1, "domestication": 1, "drill": 1, "drilling": 1, "exercise": 1, "inculcation": 1, "indoctrination": 1,
    "limitation": 1, "orderliness": 1, "self-command": 1, "self-government": 1, "strictness": 1, "subordination": 1,
    "willpower": 1, "self-mastery": 1, "disciplines": 1, "energetic": 1, "active": 1, "aggressive": 1, "dynamic": 1,
    "enterprising": 1, "industrious": 1, "lively": 1, "powerful": 1, "spirited": 1, "sprightly": 1, "spry": 1,
    "strong": 1, "tireless": 1, "vigorous": 1, "animated": 1, "ball of fire": 1, "breezy": 1, "brisk": 1, "demoniac": 1,
    "driving": 1, "forcible": 1, "fresh": 1, "hardy": 1, "high-powered": 1, "indefatigable": 1, "kinetic": 1,
    "lusty": 1, "peppy": 1, "potent": 1, "red-blooded": 1, "rugged": 1, "snappy": 1, "stalwart": 1, "strenuous": 1,
    "sturdy": 1, "tough": 1, "unflagging": 1, "untiring": 1, "vital": 1, "vivacious": 1, "zippy": 1, "energetically": 1,
    "unenergetic": 1, "empower": 1, "allow": 1, "entitle": 1, "entrust": 1, "grant": 1, "legitimize": 1, "permit": 1,
    "vest": 1, "accredit": 1, "capacitate": 1, "charge": 1, "commission": 1, "delegate": 1, "invest": 1, "license": 1,
    "okay": 1, "privilege": 1, "qualify": 1, "sanction": 1, "warrant": 1, "empowered": 1, "empowering": 1,
    "empowerment": 1, "determined": 1, "decisive": 1, "dogged": 1, "purposeful": 1, "resolute": 1, "resolved": 1,
    "serious": 1, "single-minded": 1, "steadfast": 1, "strong-willed": 1, "stubborn": 1, "tenacious": 1, "bent": 1,
    "decided": 1, "firm": 1, "fixed": 1, "obstinate": 1, "pat": 1, "persevering": 1, "set": 1, "settled": 1,
    "bent on": 1, "buckled down": 1, "constant": 1, "earnest": 1, "hard as nails": 1, "hardboiled": 1, "intent": 1,
    "mean business": 1, "on ice": 1, "set on": 1, "solid": 1, "strong-minded": 1, "unfaltering": 1, "unflinching": 1,
    "unhesitating": 1, "unwavering": 1, "determinedly": 1, "undetermined": 1, "charismatic": 1, "appealing": 1,
    "alluring": 1, "hypnotic": 1, "larger than life": 1, "magnetic": 1, "mesmerizing": 1, "poised": 1, "balance": 1,
    "equity": 1, "harmony": 1, "tension": 1, "antithesis": 1, "correspondence": 1, "counterbalance": 1,
    "equivalence": 1,
    "evenness": 1, "hang": 1, "parity": 1, "proportion": 1, "stasis": 1, "symmetry": 1, "even-steven": 1, "balanced": 1,
    "balancing": 1, "humor": 1, "banter": 1, "farce": 1, "fun": 1, "gag": 1, "joke": 1, "playfulness": 1, "whimsy": 1,
    "wisecrack": 1, "wit": 1, "amusement": 1, "badinage": 1, "buffoonery": 1, "clowning": 1, "comicality": 1,
    "drollery": 1,
    "facetiousness": 1, "flippancy": 1, "gaiety": 1, "happiness": 1, "jest": 1, "jesting": 1, "jocoseness": 1,
    "jocosity": 1,
    "jocularity": 1, "joking": 1, "joyfulness": 1, "kidding": 1, "levity": 1, "lightness": 1, "pleasantry": 1,
    "raillery": 1, "tomfoolery": 1, "witticism": 1, "wittiness": 1, "comicalness": 1, "high spirits": 1, "humored": 1,
    "humoring": 1, "humorless": 1, "protection": 1, "conservation": 1, "insurance": 1, "preservation": 1,
    "safeguard": 1,
    "safety": 1, "security": 1, "shelter": 1, "stability": 1, "aegis": 1, "armament": 1, "armor": 1, "assurance": 1,
    "barrier": 1, "buffer": 1, "bulwark": 1, "camouflage": 1, "certainty": 1, "charge": 1, "cover": 1, "custody": 1,
    "defense": 1, "fix": 1, "guard": 1, "invulnerability": 1, "reassurance": 1, "refuge": 1, "safekeeping": 1,
    "salvation": 1, "screen": 1, "self-defense": 1, "shield": 1, "strength": 1, "surety": 1, "tutelage": 1,
    "umbrella": 1, "ward": 1, "guarding": 1, "protecting": 1, "wardship": 1
}

cleanseDict = {
    "rigid": -1, "adamant": -1, "austere": -1, "definite": -1, "exact": -1, "fixed": -1, "hard-line": -1, "harsh": -1,
    "inflexible": -1, "intransigent": -1, "rigorous": -1, "solid": -1, "stern": -1, "stringent": -1,
    "uncompromising": -1, "unyielding": -1, "adamantine": -1, "bullheaded": -1, "changeless": -1, "chiseled": -1,
    "dead set": -1, "determined": -1, "firm": -1, "hard": -1, "incompliant": -1, "inelastic": -1, "inexorable": -1,
    "invariable": -1, "locked-in": -1, "obdurate": -1, "set": -1, "set in stone": -1, "single-minded": -1, "static": -1,
    "strait-laced": -1, "unalterable": -1, "unbending": -1, "unbreakable": -1, "unchanging": -1, "undeviating": -1,
    "unmoving": -1, "unpermissive": -1, "unrelenting": -1, "rigidity": -1, "rigidly": -1, "rigidness": -1,
    "sensitive": -1, "conscious": -1, "delicate": -1, "emotional": -1, "hypersensitive": -1, "keen": -1, "nervous": -1,
    "perceptive": -1, "precise": -1, "receptive": -1, "responsive": -1, "susceptible": -1, "tense": -1, "touchy": -1,
    "tricky": -1, "unstable": -1, "acute": -1, "feeling": -1, "fine": -1, "knowing": -1, "psychic": -1, "seeing": -1,
    "cognizant": -1, "easily affected": -1, "emotionable": -1, "high-strung": -1, "hung up": -1, "impressible": -1,
    "irritable": -1, "oversensitive": -1, "perceiving": -1, "precarious": -1, "reactive": -1, "sensatory": -1,
    "sensile": -1, "sensorial": -1, "sensory": -1, "sentient": -1, "supersensitive": -1, "ticklish": -1,
    "touchy feely": -1, "tuned-in": 1, "turned on to": -1, "umbrageous": -1, "sensitively": -1,
    "ultrasensitive": -1, "independent": 1, "autonomous": 1, "nonpartisan": 1, "self-reliant": 1, "self-sufficient": 1,
    "separate": 1, "sovereign": 1, "absolute": 1, "autarchic": 1, "autarchical": 1, "freewheeling": 1,
    "individualistic": 1, "nonaligned": 1, "on one's own": 1, "self-contained": 1, "self-determining": 1,
    "self-governing": 1, "self-ruling": 1, "self-supporting": 1, "separated": 1, "unaided": 1, "unallied": 1,
    "unconnected": 1, "unconstrained": 1, "uncontrolled": 1, "unregimented": 1, "independently": 1, "independents": 1,
    "sensual": 1, "exciting": 1, "sensuous": 1, "sexual": 1, "sexy": 1, "tactile": 1, "voluptuous": 1, "x-rated": 1,
    "animal": 1, "animalistic": 1, "arousing": 1, "bodily": 1, "carnal": 1, "debauched": 1, "delightful": 1,
    "epicurean": 1, "fleshly": 1, "heavy": 1, "hedonic": 1, "hot": 1, "lascivious": 1, "lecherous": 1, "lewd": 1,
    "libidinous": 1, "licentious": 1, "lustful": 1, "moving": 1, "pleasing": 1, "rough": 1, "sharpened": 1, "steamy": 1,
    "stimulating": 1, "stirring": 1, "unchaste": 1, "unspiritual": 1, "adaptable": 1, "compliant": 1, "flexible": 1,
    "malleable": 1, "resilient": 1, "versatile": 1, "ac-dc": 1, "adjustable": 1, "all around": 1, "alterable": 1,
    "can-do": 1, "changeable": 1, "conformable": 1, "convertible": 1, "ductile": 1, "easygoing": 1, "hanging loose": 1,
    "modifiable": 1, "moldable": 1, "plastic": 1, "pliable": 1, "pliant": 1, "supple": 1, "switch-hitting": 1,
    "tractable": 1, "variable": 1, "adaptability": 1, "unadaptable": 1, "joy": 1, "amusement": 1, "bliss": 1,
    "charm": 1, "cheer": 1, "comfort": 1, "delight": 1, "elation": 1, "glee": 1, "humor": 1, "pride": 1,
    "satisfaction": 1, "wonder": 1, "alleviation": 1, "animation": 1, "delectation": 1, "diversion": 1, "ecstasy": 1,
    "exultation": 1, "exulting": 1, "felicity": 1, "festivity": 1, "frolic": 1, "fruition": 1, "gaiety": 1, "gem": 1,
    "gladness": 1, "gratification": 1, "hilarity": 1, "indulgence": 1, "jewel": 1, "jubilance": 1, "liveliness": 1,
    "luxury": 1, "merriment": 1, "mirth": 1, "prize": 1, "rapture": 1, "ravishment": 1, "refreshment": 1,
    "rejoicing": 1, "revelry": 1, "solace": 1, "sport": 1, "transport": 1, "treasure": 1, "treat": 1, "good humor": 1,
    "pride and joy": 1, "regalement": 1, "creative": 1, "gifted": 1, "ingenious": 1, "innovative": 1, "inventive": 1,
    "original": 1, "productive": 1, "prolific": 1, "visionary": 1, "originative": 1, "clever": 1, "cool": 1,
    "demiurgic": 1, "deviceful": 1, "fertile": 1, "hip": 1, "innovational": 1, "innovatory": 1, "inspired": 1,
    "leading-edge": 1, "stimulating": 1, "way-out": 1, "creativeness": 1, "uncreative": 1, "courage": 1, "audacity": 1,
    "bravery": 1, "daring": 1, "determination": 1, "endurance": 1, "fearlessness": 1, "firmness": 1, "fortitude": 1,
    "gallantry": 1, "grit": 1, "heroism": 1, "prowess": 1, "spirit": 1, "spunk": 1, "tenacity": 1, "valor": 1,
    "adventurousness": 1, "backbone": 1, "bravura": 1, "dash": 1, "dauntlessness": 1, "enterprise": 1, "gameness": 1,
    "guts": 1, "hardihood": 1, "intrepidity": 1, "mettle": 1, "nerve": 1, "pluck": 1, "power": 1, "pugnacity": 1,
    "rashness": 1, "recklessness": 1, "resolution": 1, "stoutheartedness": 1, "temerity": 1, "venturesomeness": 1,
    "adventuresomeness": 1, "lion-heartedness": 1, "élan": 1, "friendly": 1, "affable": 1, "affectionate": 1,
    "amiable": 1, "amicable": 1, "attentive": 1, "beneficial": 1, "chummy": 1, "cordial": 1, "familiar": 1,
    "favorable": 1, "good": 1, "helpful": 1, "loving": 1, "loyal": 1, "neighborly": 1, "peaceful": 1, "receptive": 1,
    "sympathetic": 1, "welcoming": 1, "close": 1, "faithful": 1, "kind": 1, "sociable": 1, "tender": 1, "thick": 1,
    "attached": 1, "auspicious": 1, "benevolent": 1, "benign": 1, "buddy-buddy": 1, "civil": 1, "clubby": 1,
    "comradely": 1, "conciliatory": 1, "confiding": 1, "convivial": 1, "fond": 1, "genial": 1, "kindly": 1,
    "on good terms": 1, "outgoing": 1, "peaceable": 1, "propitious": 1, "solicitous": 1, "well-disposed": 1,
    "friendlier": 1, "friendliness": 1, "success": 1, "accomplishment": 1, "achievement": 1, "advance": 1,
    "benefit": 1, "boom": 1, "fame": 1, "gain": 1, "happiness": 1, "profit": 1, "progress": 1, "prosperity": 1,
    "realization": 1, "triumph": 1, "victory": 1, "win": 1, "arrival": 1, "ascendancy": 1, "attainment": 1,
    "clover": 1, "consummation": 1, "eminence": 1, "fortune": 1, "fruition": 1, "hit": 1, "killing": 1, "laugher": 1,
    "maturation": 1, "reward": 1, "savvy": 1, "sensation": 1, "snap": 1, "strike": 1, "successfulness": 1,
    "walkaway": 1, "walkover": 1, "bed of roses": 1, "big hit": 1, "do well": 1, "easy street": 1, "flying colors": 1,
    "good luck": 1, "good times": 1, "grand slam": 1, "gravy train": 1, "happy days": 1, "lap of luxury": 1,
    "éclat": 1, "nonsuccess": 1, "successes": 1
}

liberateDict = {
    "anxiety": -1, "angst": -1, "apprehension": -1, "concern": -1, "disquiet": -1, "doubt": -1, "dread": -1,
    "jitters": -1, "misery": -1, "misgiving": -1, "mistrust": -1, "nervousness": -1, "panic": -1, "restlessness": -1,
    "suffering": -1, "suspense": -1, "trouble": -1, "uncertainty": -1, "unease": -1, "uneasiness": -1,
    "botheration": -1, "butterflies": -1, "care": -1, "creeps": -1, "disquietude": -1, "distress": -1, "downer": -1,
    "drag": -1, "fidgets": -1, "flap": -1, "foreboding": -1, "fretfulness": -1, "fuss": -1, "heebie-jeebies": -1,
    "jumps": -1, "needles": -1, "shakes": -1, "shivers": -1, "solicitude": -1, "sweat": -1, "watchfulness": -1,
    "willies": -1, "worriment": -1, "all-overs": -1, "ants in pants": -1, "cold sweat": -1, "goose bumps": -1,
    "nail-biting": -1, "pins and needles": -1, "grief": -1, "agony": -1, "anguish": -1, "bereavement": -1,
    "despair": -1, "discomfort": -1, "gloom": -1, "heartache": -1, "heartbreak": -1, "melancholy": -1, "misery": -1,
    "mourning": -1, "pain": -1, "regret": -1, "remorse": -1, "sadness": -1, "sorrow": -1, "trouble": -1,
    "unhappiness": -1, "woe": -1, "worry": -1, "affliction": -1, "care": -1, "dejection": -1, "depression": -1,
    "desolation": -1, "despondency": -1, "disquiet": -1, "distress": -1, "dole": -1, "dolor": -1, "grievance": -1,
    "harassment": -1, "infelicity": -1, "lamentation": -1, "malaise": -1, "mortification": -1, "mournfulness": -1,
    "purgatory": -1, "rue": -1, "torture": -1, "trial": -1, "tribulation": -1, "vexation": -1, "wretchedness": -1,
    "bemoaning": -1, "bewailing": -1, "deploring": -1, "lamenting": -1, "repining": -1, "guilt": -1, "culpability": -1,
    "disgrace": -1, "indiscretion": -1, "liability": -1, "regret": -1, "remorse": -1, "responsibility": -1,
    "shame": -1, "sin": -1, "stigma": -1, "answerability": -1, "blameworthiness": -1, "contrition": -1, "crime": -1,
    "criminality": -1, "delinquency": -1, "dereliction": -1, "dishonor": -1, "error": -1, "failing": -1, "fault": -1,
    "infamy": -1, "iniquity": -1, "lapse": -1, "malfeasance": -1, "malpractice": -1, "misbehavior": -1,
    "misconduct": -1, "misstep": -1, "offense": -1, "onus": -1, "penitence": -1, "self-condemnation": -1,
    "self-reproach": -1, "sinfulness": -1, "slip": -1, "solecism": -1, "transgression": -1, "wickedness": -1,
    "wrong": -1, "malefaction": -1, "peccability": -1, "fear": -1, "alarm": -1, "angst": -1, "anxiety": -1,
    "apprehension": -1, "awe": -1, "concern": -1, "despair": -1, "dismay": -1, "doubt": -1, "dread": -1, "horror": -1,
    "jitters": -1, "panic": -1, "scare": -1, "suspicion": -1, "terror": -1, "unease": -1, "uneasiness": -1, "worry": -1,
    "abhorrence": -1, "agitation": -1, "apprehensiveness": -1, "aversion": -1, "consternation": -1, "cowardice": -1,
    "creeps": -1, "discomposure": -1, "disquietude": -1, "distress": -1, "faintheartedness": -1, "fearfulness": -1,
    "foreboding": -1, "fright": -1, "funk": -1, "misgiving": -1, "nightmare": -1, "phobia": -1, "presentiment": -1,
    "qualm": -1, "reverence": -1, "revulsion": -1, "timidity": -1, "trembling": -1, "trepidation": -1, "bête noire": -1,
    "chickenheartedness": -1, "cold feet": -1, "cold sweat": -1, "recreancy": -1, "feared": -1, "fearing": -1,
    "fears": -1, "unfearing": -1, "patient": 1, "calm": 1, "forgiving": 1, "gentle": 1, "quiet": 1, "tolerant": 1,
    "long-suffering": 1, "understanding": 1, "accommodating": 1, "composed": 1, "easygoing": 1, "enduring": 1,
    "even-tempered": 1, "forbearing": 1, "imperturbable": 1, "indulgent": 1, "lenient": 1, "meek": 1, "mild": 1,
    "mild-tempered": 1, "persevering": 1, "persistent": 1, "philosophic": 1, "philosophical": 1, "resigned": 1,
    "self-possessed": 1, "serene": 1, "stoical": 1, "submissive": 1, "tranquil": 1, "uncomplaining": 1, "unruffled": 1,
    "untiring": 1, "patiently": 1, "patientness": 1, "sexual": 1, "carnal": 1, "erotic": 1, "intimate": 1,
    "passionate": 1, "reproductive": 1, "sensual": 1, "animal": 1, "animalistic": 1, "bestial": 1, "fleshly": 1,
    "generative": 1, "genital": 1, "genitive": 1, "loving": 1, "procreative": 1, "sharing": 1, "venereal": 1,
    "voluptuous": 1, "wanton": 1, "stable": 1, "balanced": 1, "calm": 1, "durable": 1, "fast": 1, "lasting": 1,
    "permanent": 1, "reliable": 1, "safe": 1, "secure": 1, "solid": 1, "steady": 1, "strong": 1, "substantial": 1,
    "abiding": 1, "anchored": 1, "enduring": 1, "established": 1, "even": 1, "firm": 1, "invariable": 1, "nailed": 1,
    "poised": 1, "set": 1, "sound": 1, "stabile": 1, "stalwart": 1, "staunch": 1, "stout": 1, "tough": 1, "uniform": 1,
    "brick-wall": 1, "deep-rooted": 1, "equable": 1, "immutable": 1, "perdurable": 1, "resolute": 1, "set in stone": 1,
    "solid as a rock": 1, "stationary": 1, "staying put": 1, "steadfast": 1, "sturdy": 1, "sure": 1, "together": 1,
    "unalterable": 1, "unchangeable": 1, "unfluctuating": 1, "unvarying": 1, "unwavering": 1, "well-built": 1,
    "well-founded": 1, "stableness": 1, "stably": 1, "grounded": 1, "alive": 1, "appreciative": 1, "apprehensive": 1,
    "attentive": 1, "awake": 1, "cognizant": 1, "conscious": 1, "familiar": 1, "informed": 1, "mindful": 1,
    "receptive": 1, "wise": 1, "acquainted": 1, "alert": 1, "appraised": 1, "apprised": 1, "au courant": 1,
    "cool": 1, "enlightened": 1, "go-go": 1, "groovy": 1, "heedful": 1, "hip": 1, "in the know": 1,
    "in the picture": 1, "into": 1, "know the score": 1, "know what's what": 1, "know-how": 1, "knowing": 1,
    "latched on": 1, "on the beam": 1, "on to": 1, "perceptive": 1, "plugged in": 1, "savvy": 1, "sensible": 1,
    "sentient": 1, "sharp": 1, "tuned-in": 1, "up on": 1, "wise to": 1, "wised up": 1, "with it": 1, "energized": 1,
    "activated": 1, "alert": 1, "animated": 1, "spirited": 1, "active": 1, "dynamic": 1, "gay": 1, "happy": 1,
    "vivacious": 1, "instinctive": 1, "impulsive": 1, "ingrained": 1, "inherent": 1, "innate": 1, "intuitive": 1,
    "natural": 1, "spontaneous": 1, "visceral": 1, "accustomed": 1, "by seat of one's pants": 1, "congenital": 1,
    "habitual": 1, "inborn": 1, "instinctual": 1, "intrinsic": 1, "intuitional": 1, "involuntary": 1, "knee-jerk": 1,
    "mechanical": 1, "native": 1, "normal": 1, "regular": 1, "rooted": 1, "second-nature": 1, "typical": 1,
    "unlearned": 1, "unmeditated": 1, "unpremeditated": 1, "unprompted": 1, "unthinking": 1, "instinctively": 1,
    "secure": 1, "protected": 1, "defended": 1, "guarded": 1, "sheltered": 1, "shielded": 1, "immune": 1,
    "impregnable": 1, "out of harm's way": 1, "riskless": 1, "unassailable": 1, "undamaged": 1, "unharmed": 1,
    "securable": 1, "secured": 1, "securely": 1, "securing": 1, "unsecurely": 1, "passionate": 1, "ardent": 1,
    "loving": 1, "romantic": 1, "wistful": 1, "amorous": 1, "aroused": 1, "concupiscent": 1, "desirous": 1,
    "erotic": 1, "heavy": 1, "hot": 1, "lascivious": 1, "libidinous": 1, "lustful": 1, "prurient": 1, "sexy": 1,
    "steamy": 1, "stimulated": 1, "sultry": 1, "turned-on": 1, "wanton": 1, "passionately": 1
}

# Making a list that stores all the dictionaries, so a final list with all the relevant words we are looking for
finalChecklist = [unityDict, intuitionDict, resolveDict, harmonyDict, miraclesDict, cleanseDict, liberateDict]

# Initializing the scores for each category
finalScores = [0, 0, 0, 0, 0, 0, 0]

# Running a for loop through the input sentence and running checking each dictionary to see if any relevant words appear
for x in inputList:
    counter = 0
    for j in finalChecklist:
        # Search for the word in the relevant dictionary. If key not found, it returns "none", so if it isn't "none", it
        # is in the dictionary
        if j.get(x, "none") != "none":
            # Look for the relevant score to incrememt by
            finalScores[counter] += j[x]
        counter += 1

# printing the output in a readable manner
outputString = "Unity Score: " + str(finalScores[0]) + "\n" + "Intuition Score: " \
               + str(finalScores[1]) + "\n" + "Resolve Score: " + str(finalScores[2]) + "\n" + "Harmony Score: " + str(
    finalScores[3]) \
               + "\n" + "Miracles Score: " + str(finalScores[4]) + "\n" + "Cleanse Score: " + str(finalScores[5]) + "\n" \
               + "Liberate Score: " + str(finalScores[6])
print(outputString)
